# Generated by Django 3.0.6 on 2021-01-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Potato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_sweet', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
