# Generated by Django 3.0.6 on 2021-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="teacher_request",
            field=models.BooleanField(default=False),
        ),
    ]
