# Generated by Django 3.0.6 on 2021-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_pointsgained_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='colour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
