# Generated by Django 3.0.6 on 2021-03-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_user_share_code'),
        ('backend', '0006_passwordresetcode'),
    ]

    operations = [
    ]
