openapi: 3.0.0
info:
  title: API
  version: '1.0'
  contact:
    name: Group D Team
  description: ''
servers:
  - url: 'http://localhost:8000/api'
paths:
  /users:
    post:
      summary: ''
      operationId: post-users
      responses:
        '201':
          description: Created - User created.
        '400':
          description: 'Bad Request - {description of why the request is bad}'
      description: Register a user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Unique.
                email:
                  type: string
                  description: Unique.
                first_name:
                  type: string
                last_name:
                  type: string
                password:
                  type: string
                password_repeat:
                  type: string
                is_teacher:
                  type: boolean
                  description: "Bool to whether the user is applied for a teacher's account."
              required:
                - username
                - email
                - first_name
                - last_name
                - password
                - is_teacher
                - password_repeat
  /login:
    post:
      summary: ''
      operationId: post-login
      responses:
        '200':
          description: OK - Logged in.
        '400':
          description: 'Bad Request - {description of why the request is bad}'
        '404':
          description: Not Found - User does not exist.
      description: Login a user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
  /logout:
    post:
      summary: ''
      operationId: post-logout
      responses:
        '200':
          description: OK - Logged out.
      description: Logout the user.
  '/communities/{id}/posts':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: ''
      operationId: post-create_post
      responses:
        '201':
          description: 'Created post '
          headers: {}
        '400':
          description: 'Bad Request - {description of why the request is bad}'
        '401':
          description: Unauthorized User
        '404':
          description: Not Found - Community not found
      description: Provides an endpoint to create a post in a specific community
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                post_type:
                  type: string
              required:
                - title
                - description
                - post_type
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      parameters: []
    get:
      summary: ''
      operationId: get-community-id
      responses:
        '200':
          description: OK
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
  /users/feed:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_pages:
                    type: integer
                  previous_page:
                    type: integer
                  next_page:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
                required:
                  - total_pages
                  - data
        '401':
          description: Unauthorized - Login required.
      operationId: get-users-feed
      description: |-
        Get the feed posts for the logged in user.

        Pagination included: Every page has 20 posts.
      parameters:
        - schema:
            type: integer
          in: query
          name: page
          description: page number to get
  /communities:
    post:
      summary: ''
      operationId: post-community
      responses:
        '201':
          description: Community Created
        '400':
          description: Bad Request - Name and description are required
        '401':
          description: Unauthorized - Login required
        '409':
          description: Conflict - Name is already in use
      description: Create a new community
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
                - name
                - description
        description: "'name' is the name of the community to be created, 'description' is a description of the community to be created."
    parameters: []
    get:
      summary: ''
      operationId: get-communities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: List of communities
                properties:
                  total_pages:
                    type: integer
                  previous_page:
                    type: integer
                  next_page:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CommunitySimple'
                required:
                  - total_pages
                  - data
        '400':
          description: 'Bad Request - {description of why the request is bad}'
        '401':
          description: Unauthorized - Login required
      description: Get a (paginated) list of communities (ordered alphabetically by community name)
      parameters:
        - schema:
            type: string
            enum:
              - all
              - created
              - memberof
          in: query
          name: type
          description: type of list to generate
          required: true
        - schema:
            type: integer
          in: query
          name: page
          description: number of the page to retrieve (defaults to 1)
  '/communities/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: ''
      operationId: post-communitie-id
      responses:
        '200':
          description: 'Joined successfully '
        '401':
          description: Unauthorized - Login required.
        '404':
          description: 'Not found - No community with the id "{id}" exists'
        '409':
          description: Conflict - The user is already a member of that community
      description: Join a community
    get:
      summary: ''
      operationId: get-communities-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommunityFull'
        '401':
          description: Unauthorized - Login required.
        '404':
          description: 'Not found - No community with the id "{id}" exists'
      description: Get an individual community.
  '/communities/{id}/posts/{id}/likes':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: ''
      operationId: post-communities-id-posts-id-likes
      responses:
        '200':
          description: OK - Post liked.
        '401':
          description: Unauthorized - Login required / Member not part of community.
        '404':
          description: Not Found - Community/Post does not exists.
        '409':
          description: Conflict - Post is already liked.
      description: Like a post in a community.
    delete:
      summary: ''
      operationId: delete-communities-id-posts-id-likes
      responses:
        '200':
          description: OK - Post unliked.
        '401':
          description: Unauthorized - Login required.
        '404':
          description: Not Found - Community/Post/Like does not exist.
      description: Unlike a post.
  '/communities/{id}/posts/{id}/comments/{id}/likes':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
      - schema:
          type: string
        name: id
        in: path
        required: true
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: ''
      operationId: post-communities-id-posts-id-comments-id
      responses:
        '200':
          description: OK - Comment liked.
        '401':
          description: Unauthorized - Login required / User not member of community.
        '404':
          description: Not Found - Comment not found.
        '409':
          description: Conflict - Comment is already liked.
      description: Like a comment.
    delete:
      summary: ''
      operationId: delete-communities-id-posts-id-comments-id-likes
      responses:
        '200':
          description: OK - Comment unliked.
        '401':
          description: Unauthorized - Permission denied.
        '404':
          description: Not Found - Comment/Like does not exist.
      description: Unlike a comment.
  '/communities/{id}/posts/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  post:
                    $ref: '#/components/schemas/Post'
                  comments:
                    type: object
                    properties:
                      total_pages:
                        type: integer
                      previous_page:
                        type: integer
                      next_page:
                        type: integer
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Comment'
                required:
                  - post
                  - comments
              examples: {}
        '401':
          description: Unauthorised - Login required / User must be member of community.
        '404':
          description: Not Found - Post not found
      operationId: get-communities-id-posts-id
      description: |-
        Get a post by id.
        This includes the comments paginated.
      parameters:
        - schema:
            type: integer
          in: query
          name: page
          description: Page number to get.
  '/communities/{cid}/posts/{pid}/comments':
    parameters:
      - schema:
          type: string
        name: cid
        in: path
        required: true
      - schema:
          type: string
        name: pid
        in: path
        required: true
    post:
      summary: ''
      operationId: post-communities-cid-posts-pid-comments
      responses:
        '201':
          description: Comment created
        '400':
          description: Bad Request - Must include comment string.
        '401':
          description: Unauthorized - Login required.
        '404':
          description: 'Not Found - No post/comment with id "{id}" exists.'
      description: Add a comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                comment:
                  type: string
                  description: String body of comment
              required:
                - comment
        description: Content of the comment to post.
  /users/me:
    put:
      summary: ''
      operationId: put-users-me
      responses:
        '200':
          description: OK - User updated.
        '400':
          description: 'Bad Request - {description of why request is bad}'
        '401':
          description: Unauthorized - Login required.
      description: Settings endpoint.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_repeat:
                  type: string
                  description: Required if password is set.
                first_name:
                  type: string
                last_name:
                  type: string
                hide_leaderboard:
                  type: boolean
                  description: True if user wishes to hide leaderboard.
                username:
                  type: string
              required:
                - email
                - first_name
                - last_name
                - hide_leaderboard
                - username
        description: Password can be updated individually without all the other fields being required.
    get:
      summary: ''
      operationId: get-users-me
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - Login required.
      description: Get logged in user profile.
  '/users/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - Login required.
        '404':
          description: Not Found - User does not exist.
      operationId: get-users-id
      description: Get individual user profile.
components:
  schemas:
    Post:
      title: Post
      type: object
      description: Post serializer for standard display of Posts.
      properties:
        id:
          type: integer
        community:
          $ref: '#/components/schemas/CommunitySimple'
        user:
          $ref: '#/components/schemas/UserSimple'
        title:
          type: string
        description:
          type: string
        post_type:
          type: string
          description: 'Either "discussion" or "questions".'
        created_at:
          type: string
        likes_num:
          type: integer
          description: Number of likes.
        comments_num:
          type: integer
          description: Number of comments.
        is_community_owner:
          type: boolean
          description: True if the creator of the post is the community owner.
        is_liked:
          type: boolean
          description: True if the logged in user had liked this post.
      required:
        - id
        - community
        - user
        - title
        - description
        - post_type
        - created_at
        - likes_num
        - comments_num
        - is_community_owner
        - is_liked
    CommunitySimple:
      title: CommunitySimple
      type: object
      description: Simple community serializer.
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
      required:
        - id
        - name
        - description
    UserSimple:
      title: UserSimple
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        points:
          type: integer
        is_teacher:
          type: boolean
      required:
        - id
        - username
        - points
        - is_teacher
      description: Simple user serializer
    CommunityFull:
      title: CommunityFull
      type: object
      description: Detailed community serialiser.
      properties:
        creator:
          $ref: '#/components/schemas/UserSimple'
        name:
          type: string
        description:
          type: string
        created_at:
          type: string
          description: 'ISO8601 timestamp yyyy-mm-ddThh:mm:ss.sTDZ'
      required:
        - creator
        - name
        - description
        - created_at
    Comment:
      title: Comment
      type: object
      description: CommentSimple
      properties:
        user:
          $ref: '#/components/schemas/UserSimple'
        comment:
          type: string
        comment_likes:
          type: integer
        is_approved:
          type: boolean
        created_at:
          type: string
        is_liked:
          type: boolean
          description: True if the logged in user has liked this comment.
      required:
        - user
        - comment
        - comment_likes
        - created_at
    User:
      title: User
      type: object
      description: User data for profile with points attached.
      properties:
        id:
          type: integer
        username:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        points:
          type: integer
        is_teacher:
          type: boolean
          description: True if user is teacher.
        leaderboard_position:
          type: integer
          description: '[Optional] If user has hide_leaderboard False.'
        graphs:
          type: object
          properties:
            recent:
              type: array
              description: |-
                Activity in the last 4 weeks.
                Each object is a week.
              items:
                type: object
                properties:
                  name:
                    type: string
                  points:
                    type: integer
            top_communities:
              type: array
              description: |-
                Top 3 most used communities.
                Each object is a community.
              items:
                type: object
                properties:
                  community:
                    $ref: '#/components/schemas/CommunitySimple'
                  points:
                    type: integer
      required:
        - id
        - username
        - first_name
        - last_name
        - points
        - is_teacher
